#!/usr/bin/ruby

# Example script that does option parsing.

# Author::    Drew Sullivan  (mailto:drew@ss.org)
# Copyright:: Copyright (c) 2014 Drew Sullivan
# License::   GPL

require 'optparse'

#------------------------------------------------------------------------------
# Globals
#------------------------------------------------------------------------------
$debug = false

#------------------------------------------------------------------------------
def main
	OptionParser.new do |o|
	  o.banner = "Usage: #{$0} [options]"
	  o.on('-?', '--Help', 'Usage help')      { puts o; exit }
	  o.on('-x', '--[no]-debug', 'Debug on' ) { |b| $debug = true }
	  o.on('-f FILENAME', 'process :' )       { |filename| $filename = filename }
	  o.parse!
	end

	### p :debug => $debug, :filename => $filename

	puts "Does nothing.\n" if $debug;

	#### p ARGV
	ARGV.each do |arg|
		p arg
	end
end # main

#------------------------------------------------------------------------------
# run the main program
#------------------------------------------------------------------------------
main
exit
